################################################################################
### Data description
# paired-end sequencing data
# read length : could be different depending on the study
# strand-specific : unstranded
# watch out the parameters of cutadapt/star/rsem/featureCounts based on the above information
################################################################################
options:
 paired: True

samples: '/data/Storage_DAS02/home2/menteeC/mRNA/laidd_snakemake_rnaseq/samples.csv'
#e.g, /DAT^BA/projects/j.bhin/Daniel_FGFR2/FM_pdx/pipeline/samples.test.csv

################################################################################
# all output folders will be generated here
# folder of raw files should be also in this path
path:
 default: '/data/Storage_DAS02/home2/menteeC/mRNA/data'


################################################################################
# Rules
################################################################################
cutadapt:
 threads: 8
 options:
  - -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA # ILLUMINA TrueSeq R1
  - -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT # ILLUMINA TrueSeq R2 for paired-seq
  - --minimum-length 30
  - -q 20

star_align:
 index:  '/data/Storage_DAS02/home2/menteeA/reference_genome_GC' # STAR Genome index
 threads: 8
 options:

sambamba_index:
 threads: 4
 options:

featureCounts:
 gtf: '/data/Storage_DAS02/home2/menteeA/ref_primary_assembly/Homo_sapiens.GRCh38.104.gtf'
 threads: 8
 options:
  - -p # pair-end
  - -s 0 # 0: unstranded, 1: stranded, 2: reversely stranded
  - -O # consider the reads or read-pairs that overlaps with multiple exons or genes

